[project]
name = "primapy"
version = "0.0.1"
dependencies = [
	"numpy"
]

[tool.setuptools.packages.find]
where = ["src"]  # ["."] by default
exclude = ["primapy.examples*"]  # empty by default

[tools.ruff]
line-length=88
select= ["D"]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
