language: Fortran
arch:
  - amd64
  - ppc64le
  - s390x
  - arm64
os: 
  - linux
  - osx

before_install:
  - sudo apt-get -y install gfortran

script:
  - cd fsrc/examples; make; cd ../newuoa; make gverify; make gverifym; make clean

before_install:
  - brew install gcc
script:
  - cd fsrc/examples; make; cd ../newuoa; make gverify; make gverifym; make clean
