language: Fortran
arch:
  - amd64
  - ppc64le
  - s390x
  - arm64
os: 
  - linux
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install gcc; else sudo apt-get -y install gfortran; fi

script:
  - cd fsrc/examples; make; cd ../newuoa; make gverify; make gverifym; make clean
