name: Test MATLAB

on:
  # Trigger the workflow on push or pull request
  push:
  #pull_request:  # DANGEROUS! MUST be disabled for self-hosted runners!
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    - cron: '0 1, * * *'
  # Trigger the workflow manually
  workflow_dispatch:

jobs:
  test:
    name: Test MATLAB
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-latest, macos-11, macos-latest, windows-2019]   # MEX Fortran does not work on windows-latest yet
        matlab: [R2020a, R2020b, R2021a, R2021b, R2022a, latest]
        # Below R2022a, MEX is extremely slow on macOS; R2020a/b are not available on Windows.
        exclude:
          - os: macos-11
            matlab: R2020a
          - os: macos-11
            matlab: R2020b
          - os: macos-11
            matlab: R2021a
          - os: macos-11
            matlab: R2021b
          - os: macos-latest
            matlab: R2020a
          - os: macos-latest
            matlab: R2020b
          - os: macos-latest
            matlab: R2021a
          - os: macos-latest
            matlab: R2021b
          - os: windows-2019
            matlab: R2020a
          - os: windows-2019
            matlab: R2020b
          # - os: windows-latest
          #   matlab: R2020a
          # - os: windows-latest
          #   matlab: R2020b
          # - os: windows-latest
          #   matlab: R2021a
          # - os: windows-latest
          #   matlab: R2021b

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Link gfortran for MATLAB on Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          GFVER=12
          if [[ "${{ matrix.os }}" = "ubuntu-20.04" ]] ; then
              GFVER=11
          fi
          if [[ "${{ matrix.matlab }}" = "R2020a" || "${{ matrix.matlab }}" = "R2020b" \
             || "${{ matrix.matlab }}" = "R2021a" || "${{ matrix.matlab }}" = "R2021b" ]] ; then
              GFVER=9
          fi
          bash .github/scripts/link_gfortran "$GFVER"

      - name: Install Intel oneAPI on macOS
        if: startsWith(matrix.os, 'macos')
        run: bash .github/scripts/install_oneapi_macos.sh

      - name: Install Intel oneAPI on Windows
        if: startsWith(matrix.os, 'windows')
        run: cmd.exe "/K" '".github\scripts\install_oneapi_windows.bat"'

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1.2.3
        with:
          release: ${{ matrix.matlab }}

      - name: Conduct the test
        uses: matlab-actions/run-command@v1.1.2
        with:
          command: |
              ver;
              root_dir = pwd();
              cd(root_dir);
              options = struct();
              options.debug=true;
              setup(options);
              testprima;
              setup
              setup path
              testprima;
              setup cobyla
              setup uobyqa
              setup newuoa
              setup bobyqa
              setup lincoa
              setup path
              setup clean
              setup path
              setup uninstall
              setup path
              setup uninstall
              cd(fullfile(root_dir, 'matlab', 'tests')); pdv
