name: Test MATLAB

on:
  # Trigger the workflow on push or pull request
  push:
  pull_request:
  # Trigger the workflow by cron
  schedule:
    - cron: '0 4 * * 0'
    - cron: '0 16 * * 0'
  # Trigger the workflow when it is manually triggered
  workflow_dispatch:

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  my-job:
    name: Run MATLAB tests
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run script
        uses: matlab-actions/run-command@v1
        with:
          command: setup newuoan; cd ./OPDFO; setup newuoa; cd ../; options.maxdim=100;options.type='u'; verify({'newuoan', 'newuoa'},options);
