name: Test NAGFOR

on:
  # Trigger the workflow on push or pull request
  push:
  pull_request:
  # Trigger the workflow by cron
  schedule:
    - cron: '0 4 * * *'
    - cron: '0 16 * * *'
  # Trigger the workflow when it is manually triggered
  workflow_dispatch:

jobs:
  test:
    name: Run NAG tests
    runs-on: [self-hosted, nagfor]
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Conduct the test
        run: |
          source ~/local/bin/nag_licensing
          cd fsrc/test
          make clean
          make ntest

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          path: fsrc/test/log/*.log
