name: Test nagfor

on:
  # Trigger the workflow on push or pull request
  #push:
  #pull_request:  # DANGEROUS! MUST be disabled for self-hosted runners!
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    - cron: '0 19 * * *'
  # Trigger the workflow manually
  workflow_dispatch:

jobs:

  test:
    name: Run nagfor tests
    runs-on: [self-hosted, nagfor]
    strategy:
      fail-fast: false
      matrix:
        ikind: [i2]
        solver: [newuoa, cobyla, lincoa, bobyqa, uobyqa]
        fflags: [-O1, -O2, -g, -fast]   # Expensive, ignore -O3
        testdim: [small, big]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set miscellaneous environment variables
        run: bash .github/scripts/misc_env

      - name: Conduct the test
        run: |
          export PATH=$PATH:"~/local/bin"
          source ~/local/bin/nag_licensing || echo "\n\nNAG licensing failed.\n\n"
          cd "$ROOT_DIR"/fortran/tests
          if [[ -f test_cobyla.f90 ]]; then
              $SEDI 's|bign = 120|bign = 110|g' test_cobyla.f90
          fi
          export FFLAGS=${{ matrix.fflags }} && export TESTDIM=${{ matrix.testdim }} && make ntest_${{ matrix.ikind }}.${{ matrix.solver }}
          cd "$ROOT_DIR"/fortran/examples/${{ matrix.solver }} && make ntest

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.TEST_DIR }}/prima/fortran/tests/test.${{ matrix.solver }}/log/*.log

      - name: Remove the test data
        run: rm -rf ${{ env.TEST_DIR }}
