name: Test Absoft

on:
  # Trigger the workflow on push or pull request
  #push:
  #pull_request:  # DANGEROUS! MUST be disabled for self-hosted runners!
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    - cron: '0 20 * * *'
  # Trigger the workflow manually
  workflow_dispatch:

jobs:

  test:
    name: Run Absoft tests
    runs-on: [self-hosted, absoft]
    strategy:
      fail-fast: false
      matrix:
        ikind: [i2]  # [i2, i4, i8] fails due to unavailability of license servers
        solver: [newuoa, cobyla, lincoa, bobyqa, uobyqa]
        fflags: [-g, -O3]  # -fast always runs overtime. Bug of compiler?

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Miscellaneous setup
        run: bash .github/scripts/misc_setup

      - name: Conduct the test
        run: |
          LOCAL="$HOME/local"
          AFDIR="$(find "$LOCAL" -maxdepth 2 -name "absoft[0-9]*" -type d -print | sort | tail -n 1)"
          source "$AFDIR"/bin/absvars.sh
          export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH
          cd "$ROOT_DIR"/fortran/tests && export FFLAGS=${{ matrix.fflags }} && make atest_${{ matrix.ikind }}.${{ matrix.solver }}
          cd "$ROOT_DIR"/fortran/examples/${{ matrix.solver }} && make atest

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.TEST_DIR }}/prima/fortran/tests/test.${{ matrix.solver }}/log/*.log

      - name: Remove the test data
        run: rm -rf ${{ env.TEST_DIR }}
