name: Test Flang in AMD AOCC

on:
  # Trigger the workflow on push or pull request
  #push:
  #pull_request:
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    - cron: '0 4 1-31/3 * *'
  # Trigger the workflow manually
  workflow_dispatch:


jobs:

  test:
    name: Run AOCC Flang tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ikind: [i2]
        solver: [newuoa, cobyla, lincoa, bobyqa, uobyqa]
        fflags: [-O1, -O2, -O3, -g, -fast]
        testdim: [small, big]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install AOCC
        run: bash .github/scripts/install_aocc

      - name: Set TEST_DIR
        run: bash .github/scripts/set_test_dir

      - name: Conduct the test
        run: |
          ROOT="$(cd "$(dirname "./")"; pwd -P)/$(basename "./")"  # `realpath` is unavailable on macOS
          cd $ROOT/fortran/${{ matrix.solver }} && bash ./flint --all && bash ./mlint --all
          cd $ROOT/fortran/tests && export FFLAGS=${{ matrix.fflags }} && export TESTDIM=${{ matrix.testdim }} && make dtest_${{ matrix.ikind }}.${{ matrix.solver }}
          cd $ROOT/fortran/examples/${{ matrix.solver }} && make dtest

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.TEST_DIR }}/prima/fortran/tests/test.${{ matrix.solver }}/log/*.log

      - name: Remove the test data
        run: rm -rf ${{ env.TEST_DIR }}
